/* Editor workflow modes — standalone pack authoring */
(function()
{
	"use strict";

	const MODES = {
		clothing: {
			id: "clothing",
			label: "Clothing",
			packType: "clothing",
			saveTarget: "mods",
			pieceLabel: "Clothing piece",
			layersTitle: "Clothing pieces",
			hint: "Author wearables with one full-coverage base PNG per pose, then optional displacement masks (cut away cloth) instead of redrawing every state.",
			showCotBindings: true,
			showPieceList: true,
			showAddPiece: true,
			showPackMeta: true,
			previewStack: ["base", "editor"],
		},
		"base-poses": {
			id: "base-poses",
			label: "Base poses",
			packType: "base",
			saveTarget: "base-pack",
			pieceLabel: "Body",
			layersTitle: "Base body",
			hint: "Replace the default doll body per pose — your own look or higher-resolution art. Saves to base-pack/ and loads at runtime (no HTML rebake).",
			showCotBindings: false,
			showPieceList: false,
			showAddPiece: false,
			showPackMeta: false,
			previewStack: ["editor"],
		},
		makeup: {
			id: "makeup",
			label: "Makeup",
			packType: "makeup-overlay",
			saveTarget: "mods",
			pieceLabel: "Makeup piece",
			layersTitle: "Makeup overlays",
			hint: "Base faces, distinguishing feature overlays, hair, makeup, and body writing. Base faces bind to person[\"paperdoll face\"]; distinguishing overlays bind to one distinguishing mark (like NPC chargen).",
			showCotBindings: false,
			showMakeupBindings: true,
			showPieceList: true,
			showAddPiece: true,
			showPackMeta: true,
			showRecolor: true,
			previewStack: ["base", "editor"],
		},
		skin: {
			id: "skin",
			label: "Skin & tattoos",
			packType: "skin-overlay",
			saveTarget: "mods",
			defaultLayer: "skin",
			baseZIndex: 18,
			pieceLabel: "Skin / tattoo piece",
			layersTitle: "Skin overlays",
			hint: "Tattoos, markings, and skin details drawn above the base body (includes tattoo-style art).",
			showCotBindings: false,
			showPieceList: true,
			showAddPiece: true,
			showPackMeta: true,
			showLayerCategory: true,
			layerCategoryLabel: "Skin layer",
			previewStack: ["base", "editor"],
		},
		wet: {
			id: "wet",
			label: "Wet / cum",
			packType: "effect-overlay",
			saveTarget: "mods",
			defaultLayer: "wet",
			effectKind: "wet",
			baseZIndex: 72,
			pieceLabel: "Wet / cum piece",
			layersTitle: "Effect overlays",
			hint: "Wet skin, cum, and similar effects drawn on top of clothing.",
			showCotBindings: false,
			showPieceList: true,
			showAddPiece: true,
			showPackMeta: true,
			showLayerCategory: true,
			layerCategoryLabel: "Wet / cum layer",
			previewStack: ["base", "editor"],
		},
	};

	window.ExhibitionPackModes = {
		MODES: MODES,
		ORDER: ["clothing", "makeup", "base-poses", "skin", "wet"],
		DEFAULT_APPEARANCE_PACK_ID: "appearance-mod",
		LEGACY_PACK_IDS: {
			clothing: "clothing-mod",
			skin: "skin-mod",
			makeup: "makeup-mod",
			wet: "wet-mod",
		},
		get(modeId) { return MODES[modeId] || MODES.clothing; },
	};
})();